HTTP/1.1 200 OK
Server: A gameboy :3
Content-Type: text/html; charset=utf-8
Content-Language: fr-FR

<link rel="icon" href="data:image/png;base64,iVBORw0KGgo="><style>body{text-align:center;font-family:sans-serif;color:#222;width:600px;margin:auto;}</style><h1>Le serveur de cette page est une gameboy :3</h1><p>Avec son indécente vitesse de CPU de 4MHz, 8Ko de RAM, 1Ko/s de transfer en série elle est tout de même capable de supporter des requêtes HTTP.</p><p>Vous n'avez aucune excuse ♥</p><p>Si vous avez des questions, vous trouverez les réponses <a href="/why">ici</a></p><p>Astatine est fière de ses bêtises :3</p>
