HTTP/1.1 200 OK
Server: A gameboy :3
Content-Type: text/html; charset=utf-8
Content-Language: en-US

<link rel="icon" href="data:image/png;base64,iVBORw0KGgo="><style>body{text-align:center;font-family:sans-serif;color:#222;width:600px;margin:auto;}</style><h1>This page is being served by a gameboy :3</h1><p>With its insane 4MHz CPU speed, 8KB of RAM, 1KB/s serial transfer speed it's still able to handle http requests.</p><p>You have no excuses ♥</p><p>If you have any questions, find the answers <a href="/why">here</a></p><p>Made with smug by Astatin :3</p>
