HTTP/1.1 200 OK
Server: A gameboy :3
Content-Type: text/html; charset=utf-8
Content-Language: en-US

<link rel="icon" href="data:image/png;base64,iVBORw0KGgo="><style>body{text-align:center;font-family:sans-serif;color:#222;width:600px;margin:auto;}</style><h1>Why am I doing this ?</h1><p>Why not ? :3</p><p><a href="/">Click here to return to index</a></p><p>Made with smug by Astatin :3</p>
